### ISSUE TITLE
Weird coloring using "_"

### ISSUE THREAD

**Issue by PierreMarchand20** [Aerijo/language-latex2e#12]
See the following examples:
![capture d ecran 2018-02-05 a 14 33 26](https://user-images.githubusercontent.com/15056323/35806973-96ba16fa-0a81-11e8-95b6-9148878a1265.png)
![capture d ecran 2018-02-05 a 14 33 31](https://user-images.githubusercontent.com/15056323/35806974-96d7de7e-0a81-11e8-9fb4-e3b8697782cc.png)
![capture d ecran 2018-02-05 a 14 33 36](https://user-images.githubusercontent.com/15056323/35806975-96f0f6d4-0a81-11e8-87dc-9e13fbca32f3.png)

**Comment by Aerijo** [comment]
@PierreMarchand20 I was unable to reproduce this with what you've shown.

<img width="336" alt="screen shot 2018-02-06 at 6 18 47 pm" src="https://user-images.githubusercontent.com/22167388/35846301-393d03ae-0b6a-11e8-9000-25b017c3c33e.png">

```latex
$(\Gamma_p)_{p=1}^{n}$
$E_p$
\include{structure/schwarz_methods}
```

You did remind me to remove the underscore/subscript rule in text mode though, so try the latest patch (v0.13.4).

If your issues still persist, try posting a full MWE that demonstrates the issue & I can copy and paste it.

**Comment by PierreMarchand20** [comment]
It is hard to find a MWE, I have a big file and the coloring is broken at several places but I will try to find what makes it broken.

**Comment by PierreMarchand20** [comment]
Ok, first, an easy one: 
```
\begin{theorem}[Well]{\cite{Something}}]     
 stuff  
\end{theorem}
```
![capture d ecran 2018-02-06 a 09 50 05](https://user-images.githubusercontent.com/15056323/35849806-21ad3d04-0b23-11e8-9af4-42f721abd358.png)

You have to put this extra bracket to cite at this place with an optional argument (see https://tex.stackexchange.com/questions/13945/cite-in-theorem-environment-argument)

**Comment by PierreMarchand20** [comment]
Apart from my last message, I do not see any other problem with the last update 👍

**Comment by Aerijo** [comment]
@PierreMarchand20 That's a tricky problem to solve given the tools I have. I've released a patch that addresses your issue with the brackets, but it introduces it's own problems. For example, this will not be right:
```latex
\begin{itemize}[{\cite[Well]{Something}} ]  [ [ [ [ [ [ [ [ [ ] ] ] ] 
  \item this
\end{itemize}
```

Checking the scope anywhere in those last brackets shows the whole thing is considered part of the optional argument. I don't think I can fix this (easily / at all), so you'll have to wait until the entirely revamped / new improved grammar comes out.

**Comment by PierreMarchand20** [comment]
Ah yes, I saw that there was something with `tree-sitter` coming up. Do you still want feedbacks for `language-latex2e` ? may be it does not worth it if everything is going to change anyway

**Comment by Aerijo** [comment]
I'll still be releasing bug fixes like I am now, but I'm focusing on writing the new one.

Does the first problem in this issue still happen? What are the scopes at the opening parenthesis `(`, the `Gamma` command, the first `p`, and the `=`? I hope you can find a way to make a MWE.

BTW, I recommend applying some of those styles I showed you. They help bring out the capabilities of the grammar, and make package and environments distinct.

**Comment by PierreMarchand20** [comment]
Since the last update (v0.13.4), I do not have the issue again, thanks 👍  What do you mean by "making package and environments distinct" ?

**Comment by Aerijo** [comment]
Different colours

It looks boring if it's all the same.

**Comment by Aerijo** [comment]
Just a quick check though: in your examples, does the scope `markup.other.math.inline.latex` exist between the dollar signs? If it doesn't, that could be a sign of unbalanced math delimiters (or undetected ones). It would explain why stuff is white.

**Comment by PierreMarchand20** [comment]
Well, I do not have an example anymore since it is fixed with the last update :-)
