### ISSUE TITLE
Compilation in .tikz file

### ISSUE THREAD

**Issue by PierreMarchand20** [Aerijo/language-latex2e#14]
I cannot compile from a `.tikz` file containing the line `% !TEX root = ../main.tex` using the package `Latex` you suggested. I post this issue here because I guess it is an issue with the grammar, but I can post the issue in the other package too.

**Comment by Aerijo** [comment]
Nope, it looks like it's being thrown because it doesn't recognise the `.tikz` extension as valid (even though the magic comment points to the real root file)

```
isSourceFile (filePath) {
    return filePath && !!filePath.match(/\.(?:tex|lhs|lagda|[prs]nw)$/i)
  }
```

I'll write a PR on the `latex` package.

**Comment by Aerijo** [comment]
...or I won't. The [commit](https://github.com/Aerijo/atom-latex/commit/b09c1b4950461570c2262f2d138330fd700efc0a) has already been made, but not released. It should be safe then for you to edit this manually, as any future releases will have the fixed version anyway.

1. Go to the following file: `~/.atom/packages/latex/lib/werkzeug.js`

2. Replace lines 39 -- 41 with
```js
  isSourceFile (filePath) {
    return filePath && !!filePath.match(/\.(?:tex|tikz|lhs|lagda|[prs]nw)$/i)
  },
```

**Comment by PierreMarchand20** [comment]
Oh ok thank you !
