### ISSUE TITLE
auto-detect broken

### ISSUE THREAD

**Issue by PierreMarchand20** [Aerijo/language-latex2e#15]
Since the last update of atom, auto-detect does not work for `.tex` files. I guess it is due to the changes in the API (http://blog.atom.io/2018/02/13/atom-1-24.html)

**Comment by Aerijo** [comment]
I actually ran into this issue earlier today, with another package I had made a PR to. I was experiencing the buggy behaviour too, but didn't think it was linked to what it ended up being.

The issue itself wasn't any recent change in the API; it was my addition of an `injectionSelector` property in the main grammar. This ideally allows it to insert itself into markdown, when one writes the following
````
```latex
Proper \LaTeX syntax highlighting
```
````

However, this caused a bug where it would no longer get applied to the actual file for some reason. The change I released isolates injections to a separate file, so they still work but they don't cause the bug.
