### ISSUE TITLE
overline command

### ISSUE THREAD

**Issue by PierreMarchand20** [Aerijo/language-latex2e#16]
`linter-spell-latex` does not recognize `\overline`. I noticed that it is not in the scope as other commands, so I am guessing it is an issue with the grammar, but I may be wrong.
![capture d ecran 2018-02-16 a 10 05 15](https://user-images.githubusercontent.com/15056323/36300278-eb95e97e-1300-11e8-98a1-8d049275f775.png)
The scopes of `\overline` are:
![capture d ecran 2018-02-16 a 10 05 36](https://user-images.githubusercontent.com/15056323/36300289-fe0d6550-1300-11e8-9248-7bf72f9148c9.png)
For example, there is no issue with `\underline` and its scopes are:
![capture d ecran 2018-02-16 a 10 09 15](https://user-images.githubusercontent.com/15056323/36300389-788cca5a-1301-11e8-82ac-2c4755d67ffa.png)

**Comment by Aerijo** [comment]
You got me. My current workaround for spell check compatibility is to add a bunch of scopes it recognises to all the word stuff. Needless to say, it's not optimal. In this case, I forgot to add them to primitives. In general, it adds a bunch of useless scopes. I've released a patch for now though.

**Comment by PierreMarchand20** [comment]
ok thanks ! do you think that it will be easier with atom 1.25 and tree-sitter ?

**Comment by Aerijo** [comment]
I don't know. The whole concept of basing things on scope will change, with things like this instead being linked to an "abstract syntax tree". It will probably be similar though.
