### ISSUE TITLE
atom-autocomplete-latex-cite package does not work

### ISSUE THREAD

**Issue by werunom** [Aerijo/language-latex2e#7]
When I use this language-package, the [atom-autocomplete-latex-cite
](https://github.com/hesstobi/atom-autocomplete-latex-cite) does not work. I disabled this language-package and enabled the [language-latex](https://github.com/area/language-latex); then the autocomplete-cite works fine. 

Was not sure where to raise this issue - so, I have done this in both the places :) See [this](https://github.com/hesstobi/atom-autocomplete-latex-cite/issues/4)

**Comment by Aerijo** [comment]
I'll add a note to the README.md about what to do.

**Comment by werunom** [comment]
Thanks for the PR. works fine...
