### ISSUE TITLE
`meta.reference.latex` different scope range then `meta.citation.latex` and others

### ISSUE THREAD

**Issue by hesstobi** [Aerijo/language-latex2e#8]
The scope `meta.reference.latex` stop just before the end curly brace were as other scopes like `meta.citation.latex` and `meta.definition.latex`  including the curly end brace.

The main issue behind this is that the trigger for the autocomplete package [atom-autocomplete-latex-references](https://github.com/hesstobi/atom-autocomplete-latex-references) will not work (see the [issue](https://github.com/hesstobi/atom-autocomplete-latex-references/issues/4) ). Because the cursor is usually just before the curly brace during editing the reference.

Thus please the change the behaviour of this scope. Replaceing `contentName` with `name` should fix this. If you like a can provide a PR.

**Comment by Aerijo** [comment]
I changed `contentName` to `name`. If there's anything else, reopen this issue.
