### ISSUE TITLE
Spell checking using linter is not working

### ISSUE THREAD

**Issue by werunom** [Aerijo/language-latex2e#9]
I dont get any messages for `linter-spell` and `linter-spell-latex` when I use this language. But if I switch to `language-latex`, the spell corrections come out fine. 

Is there some tweaking I should do? You have mentioned about these linter packages [here](https://github.com/Aerijo/language-latex2e#the-hack-jobs-sorry); but there is no specific instructions  mentioned there.

Let me know...

**Comment by Aerijo** [comment]
Once again, (the poor selection of) activation hooks are getting in the way. I actually made a PR to that package, but it hasn't been acknowledged.

A quick fix is to make the change [here](https://github.com/AtomLinter/linter-spell-latex/pull/28/files), but I may as well write a package that handles that stuff.

**Comment by werunom** [comment]
Thanks. I have implemented the quick fix as of now. Will wait for the merge of the PR.

**Comment by Aerijo** [comment]
@werunom There was also an incompatibility between this package and `linter-spell`. Basically, I originally made the command name part of it's scope, so `\foo` would be `support.function.general.foo.latex`. However, `linter-spell` can only test against a set of absolute scopes; it does not have 'wildcard' capability.

I had a solution on my local version, but am not confident it will get accepted. Instead, I've released a patch for `language-latex2e` that removes this dynamic scoping, so hopefully make spell checking compatible. Chances are no one had noticed it anyway, as I still haven't listed the features.

If you do get unexpected spell checking where it shouldn't be, and it does not happen with `language-latex`, please open another issue and I'll fix it.

**Comment by werunom** [comment]
Updated the package; but the spell-check is not working yet!

Before updating the language-latex2e package, I reverted the change in `package.json` in the `linter-spell-latex`. That is, I removed the entry in the `activationHooks` section. Thought with this update, I need not do this temporary fix that you suggested. Should I still keep it to get the spell corrections?

**Comment by Aerijo** [comment]
Yes, that change was still necessary. I can't control that particular problem with an update to this package.

**Comment by werunom** [comment]
Ok. I have put it back. Thanks!
